# -*- coding: utf-8 -*-
"""stegano.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y1o0-QWJc6F6W-WO_miFqvZ1gUmaC2UV
"""

!pip install stegano

from stegano import lsb

secret = lsb.hide("about1.png", "hi i am NURUL FAJRI this is steganography")
secret.save("about1.png")

from stegano import lsb

print(lsb.reveal("about1.png"))